sudo: required
dist: xenial
language: python
python:
  - 3.6
addons:
  chrome: stable
  firefox: latest
services:
  - xvfb
before_install:
  - nvm install 10
install:
  - npm install
  - npm install -g chromedriver geckodriver webdriver
  - pip install -r requirements.txt
cache:
  npm: true
  directories:
    - $HOME/.cache/pip
before_script:
  - python manage.py migrate
  - python manage.py runserver &
script:
  - xvfb-run --server-args="-screen 0 1024x768x24" npm run test
