sudo: required
dist: trusty
language: node_js
python:
  - 3.6
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
install:
  - npm install -g chromedriver geckodriver webdriver
node_js:
  - "node"
  - "8"
  - "7"
  - "lts/*"
cache:
  directories: node_modules
before_script:
  - python manage.py runserver
