sudo: required
dist: trusty
language: python
python:
  - 3.6
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
before_install:
  - nvm install 10
install:
  - npm install -g chromedriver geckodriver webdriver
  - pip install -r requirements.txt
cache:
  npm: true
  directories:
    - $HOME/.cache/pip
before_script:
  - python manage.py migrate
  - python manage.py runserver &
script:
  - npm run test
