# Generated by Django 2.0.6 on 2018-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lastgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_code', models.IntegerField()),
                ('last_group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number_enc', models.CharField(blank=True, max_length=255, unique=True)),
                ('student_number_hash', models.CharField(blank=True, max_length=255, unique=True)),
                ('url', models.CharField(max_length=250)),
                ('participation_date', models.DateTimeField(auto_now_add=True)),
                ('device_participant', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=200)),
                ('survey_code_desktop', models.CharField(max_length=200)),
                ('survey_code_mobile', models.CharField(max_length=200)),
                ('expected_completion_time', models.CharField(default='10', max_length=200)),
                ('number_of_groups', models.IntegerField()),
                ('integration_parameter_student_enc', models.CharField(max_length=200)),
                ('integration_parameter_branching', models.CharField(blank=True, max_length=200, null=True)),
                ('last_group', models.IntegerField(default=0)),
            ],
        ),
    ]
