# Generated by Django 2.0.6 on 2018-07-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_randomizer_app', '0002_auto_20180703_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='number_of_groups',
            new_name='group_count',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_code_desktop',
            new_name='survey_desktop_url',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_code_mobile',
            new_name='survey_mobile_url',
        ),
    ]
