# Generated by Django 2.0.6 on 2018-07-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_randomizer_app', '0003_auto_20180703_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='student_number_hash',
        ),
    ]
