# Generated by Django 2.0.6 on 2018-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_randomizer_app', '0004_remove_participant_student_number_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_mobile_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
