# Generated by Django 2.0.6 on 2018-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_randomizer_app', '0005_auto_20180705_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='expected_completion_time',
            field=models.CharField(default='10', help_text='In minutes', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='group_count',
            field=models.PositiveIntegerField(help_text='The number of groups you wish to rotate'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='integration_parameter_branching',
            field=models.CharField(blank=True, help_text="Optional. The same value should be set in LimeSurvey's Panel Integration", max_length=200, null=True, verbose_name='Branching parameter'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='integration_parameter_student_enc',
            field=models.CharField(help_text="The same value should be set in LimeSurvey's Panel Integration", max_length=200, verbose_name='Student number parameter'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_desktop_url',
            field=models.CharField(help_text='Copy from LimeSurvey', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_mobile_url',
            field=models.CharField(blank=True, default='', help_text='Optional. Copy from LimeSurvey', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(help_text='Will be shown to respondents and is used for creating the URL for this survey.', max_length=200),
        ),
    ]
