# Generated by Django 2.0.6 on 2018-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_randomizer_app', '0006_auto_20180726_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='expected_completion_time',
        ),
        migrations.AddField(
            model_name='survey',
            name='screen_out_text',
            field=models.TextField(default='', help_text='This text is shown when the participant has already participated in another survey and is not allowed to participate.', verbose_name='Screen-out text'),
        ),
        migrations.AddField(
            model_name='survey',
            name='welcome_text',
            field=models.TextField(default='', help_text='This text is shown when the user enters the survey.'),
        ),
    ]
