# Generated by Django 2.0.6 on 2018-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='surveys',
            options={'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterField(
            model_name='participants',
            name='participation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
