# Generated by Django 2.0.6 on 2018-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0005_auto_20180626_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='studentnumber_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='studentnumber_enc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
