# Generated by Django 2.0.6 on 2018-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0006_auto_20180626_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expected_completion_time',
            field=models.CharField(default='10', max_length=200),
        ),
    ]
