# Generated by Django 2.0.6 on 2018-06-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0007_survey_expected_completion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='number_of_goups',
            new_name='number_of_groups',
        ),
        migrations.AddField(
            model_name='survey',
            name='last_group',
            field=models.IntegerField(default=0),
        ),
    ]
