# Generated by Django 2.0.6 on 2018-06-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0008_auto_20180628_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question_name_branching',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
