# Generated by Django 2.0.6 on 2018-06-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0010_auto_20180628_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question_parameter_branching',
            new_name='integration_parameter_branching',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question_name_student_enc',
            new_name='integration_parameter_student_enc',
        ),
    ]
