# Generated by Django 2.0.6 on 2018-06-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0003_auto_20180620_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentnumber_enc', models.TextField()),
                ('url', models.CharField(max_length=250)),
                ('participation_date', models.DateTimeField(auto_now_add=True)),
                ('device_participant', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_code_desktop', models.CharField(max_length=200)),
                ('survey_code_mobile', models.CharField(max_length=200)),
                ('survey_name', models.CharField(max_length=200)),
                ('number_of_goups', models.IntegerField()),
                ('question_name_student_enc', models.CharField(max_length=200)),
            ],
        ),
    ]
