# Generated by Django 2.0.6 on 2018-06-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0004_participant_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='Surveys',
        ),
    ]
