# Generated by Django 2.0.6 on 2018-06-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0009_survey_question_name_branching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question_name_branching',
            new_name='question_parameter_branching',
        ),
    ]
