# Generated by Django 2.0.6 on 2018-07-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0011_auto_20180628_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='studentnumber_enc',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='studentnumber_hash',
        ),
        migrations.AddField(
            model_name='participant',
            name='student_number_enc',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='student_number_hash',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
