# Generated by Django 2.0.6 on 2018-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0012_auto_20180703_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='student_number_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
