# Generated by Django 2.0.6 on 2018-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelrandomizer_app', '0013_auto_20180703_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='student_number_hash',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
